version: '3.8'

services:
  backend:
    build: ./backend
    container_name: data-microservice-backend
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - ./watch:/app/watch
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - DATA_DIR=data
      - WATCH_DIR=watch
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: data-microservice-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  data:
  watch:
