"""Add DBOptimizationResult table and relationship to DBProcessingResult

Revision ID: 898a22d31eb0
Revises: 79466b207f96
Create Date: 2025-05-26 10:21:51.895740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898a22d31eb0'
down_revision: Union[str, None] = '79466b207f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dboptimizationresult',
    sa.Column('processing_result_id', sa.Uuid(), nullable=False),
    sa.Column('optimizer_params', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['processing_result_id'], ['processingresult.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dboptimizationresult_id'), 'dboptimizationresult', ['id'], unique=False)
    op.create_index(op.f('ix_dboptimizationresult_processing_result_id'), 'dboptimizationresult', ['processing_result_id'], unique=False)
    op.create_index(op.f('ix_dboptimizationresult_status'), 'dboptimizationresult', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dboptimizationresult_status'), table_name='dboptimizationresult')
    op.drop_index(op.f('ix_dboptimizationresult_processing_result_id'), table_name='dboptimizationresult')
    op.drop_index(op.f('ix_dboptimizationresult_id'), table_name='dboptimizationresult')
    op.drop_table('dboptimizationresult')
    # ### end Alembic commands ###
